# Generated by Django 5.1 on 2024-08-23 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_rating_listing_rating_count_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('listing', 'user')},
        ),
    ]
