# Generated by Django 5.1 on 2024-08-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rating_count',
        ),
    ]
