# Generated by Django 5.1 on 2024-08-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rating',
        ),
    ]
