# Generated by Django 5.1 on 2024-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_carouselimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
