# Generated by Django 5.1 on 2024-08-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_delete_carouselimage_booking_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
    ]
