# Generated by Django 5.1 on 2024-11-05 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_message_created_at_useractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-listing']},
        ),
        # Закомментируем удаление столбцов
        # migrations.RemoveField(
        #     model_name='discount',
        #     name='discount_percentage',
        # ),
        # migrations.RemoveField(
        #     model_name='discount',
        #     name='end_date',
        # ),
        # migrations.RemoveField(
        #     model_name='discount',
        #     name='start_date',
        # ),
        # Оставляем добавление новых полей
        migrations.AddField(
            model_name='discount',
            name='applicable_to',
            field=models.CharField(default='All users', max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
