# Generated by Django 5.1 on 2024-11-09 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
